# Generated by Django 5.2.7 on 2025-10-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('donor', 'Donor'), ('patient', 'Patient'), ('hospital', 'Hospital')], default='admin', max_length=10),
        ),
    ]
