# Generated by Django 5.2.7 on 2025-10-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('donor', 'Donor'), ('patient', 'Patient'), ('hospital', 'Hospital')], default='donor', max_length=10),
        ),
    ]
