# Generated by Django 5.2.7 on 2025-10-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0007_branch_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetail',
            name='profile_photo',
            field=models.ImageField(default='donor_photos/default.jpg', upload_to='donor_photos/'),
        ),
    ]
