# Generated by Django 5.2.7 on 2025-10-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0008_alter_donordetail_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetail',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donordetail',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donordetail',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
