# Generated by Django 5.2.7 on 2025-10-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0010_bloodrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('patient', 'Patient'), ('hospital', 'Hospital')], default='donor', max_length=10),
        ),
    ]
