# Generated by Django 5.2.7 on 2025-10-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0015_hospitalbloodrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalbloodrequest',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='hospitalbloodrequest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='hospitalbloodrequest',
            name='requested_date',
        ),
        migrations.AddField(
            model_name='hospitalbloodrequest',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitalbloodrequest',
            name='required_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hospitalbloodrequest',
            name='urgency',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalbloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalbloodrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalbloodrequest',
            name='units_required',
            field=models.IntegerField(null=True),
        ),
    ]
