# Generated by Django 5.2.7 on 2025-10-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0017_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodstock',
            name='hospital',
        ),
    ]
