# Generated by Django 5.2.7 on 2025-10-28 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0018_remove_bloodstock_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodstock',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_bank_app.hospitaldetail'),
        ),
    ]
