# Generated by Django 5.2.7 on 2025-10-28 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0019_bloodstock_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='branch',
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_bank_app.hospitaldetail'),
        ),
    ]
