# Generated by Django 5.2.7 on 2025-10-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0021_hospitalbloodrequest_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
    ]
