# Generated by Django 5.2.7 on 2025-10-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0022_alter_hospitalbloodrequest_blood_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalbloodrequest',
            old_name='hospital',
            new_name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='hospitalbloodrequest',
            name='full_name',
        ),
    ]
