# Generated by Django 5.2.7 on 2025-10-30 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0024_donationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='blood_group',
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_bank_app.hospitaldetail'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_bank_app.donordetail'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
