# Generated by Django 5.2.7 on 2025-10-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0025_remove_donationrequest_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
