# Generated by Django 5.2.7 on 2025-10-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0026_alter_donationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donordetail',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
