# Generated by Django 5.2.7 on 2025-10-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0030_notification_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
