# Generated by Django 5.2.7 on 2025-10-31 15:34

import blood_bank_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0031_appointment_donation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(null=True, validators=[blood_bank_app.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='required_date',
            field=models.DateField(validators=[blood_bank_app.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='donation_date',
            field=models.DateField(blank=True, null=True, validators=[blood_bank_app.models.validate_future_date]),
        ),
    ]
