# Generated by Django 5.2.7 on 2025-10-31 16:23

import blood_bank_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0032_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='donation_date',
            field=models.DateField(blank=True, null=True, validators=[blood_bank_app.models.validate_future_date]),
        ),
    ]
