# Generated by Django 5.2.7 on 2025-11-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0034_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='appointment',
        ),
    ]
