# Generated by Django 5.2.7 on 2025-11-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0037_hospitalbloodstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalbloodstock',
            name='hospital',
        ),
    ]
