# Generated by Django 5.2.7 on 2025-11-01 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0039_hospitalbloodstock_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbloodstock',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_bank_app.hospitaldetail'),
        ),
    ]
