# Generated by Django 5.2.7 on 2025-11-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0040_alter_hospitalbloodstock_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='donor_response',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Reschedule', 'Reschedule'), ('No Response', 'No Response')], default='No Response', max_length=20, null=True),
        ),
    ]
