# Generated by Django 5.2.7 on 2025-11-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0041_alter_appointment_donor_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldetail',
            name='user',
        ),
    ]
