# Generated by Django 5.2.7 on 2025-11-04 15:40

import blood_bank_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0043_hospitaldetail_user_alter_patientdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbloodrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, null=True, validators=[blood_bank_app.models.validate_future_date]),
        ),
    ]
