# Generated by Django 5.2.7 on 2025-11-04 15:41

import blood_bank_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0044_alter_hospitalbloodrequest_requested_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbloodrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalbloodrequest',
            name='required_date',
            field=models.DateField(null=True, validators=[blood_bank_app.models.validate_future_date]),
        ),
    ]
