# Generated by Django 5.2.7 on 2025-11-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0045_alter_hospitalbloodrequest_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='donor_response',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Reschedule', 'Reschedule'), ('No Response', 'No Response')], default='No Response', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Date Sent', 'Date Sent'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Recorded', 'Recorded')], default='Pending', max_length=20, null=True),
        ),
    ]
