# Generated by Django 5.2.7 on 2025-11-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0046_alter_appointment_donor_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donordetail',
            name='next_eligible_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
