# Generated by Django 5.2.7 on 2025-11-09 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0047_donordetail_next_eligible_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='reason',
            new_name='medical_condition',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='hospital_address',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='units_required',
        ),
    ]
