# Generated by Django 5.2.7 on 2025-11-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0048_rename_reason_bloodrequest_medical_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='blood_group',
        ),
    ]
