# Generated by Django 5.2.7 on 2025-11-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0049_remove_bloodrequest_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
