# Generated by Django 5.2.7 on 2025-11-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0050_bloodrequest_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='units_required',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
