# Generated by Django 5.2.7 on 2025-11-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0051_bloodrequest_units_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
